language: python
os:
- linux
python:
- '3.6'
- '3.7'
- '3.8'
install: pip install -U pip
script:
- pip install -U .
- pip install -r requirements_dev.txt
- ls
- ls /home/travis/build
- ls /home/travis/build/zfit
- coverage run --source=/home/travis/build/zfit --branch -m pytest --basetemp={envtmpdir}
- coverage report
after_success:
- pip install coveralls
- coveralls
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: zfit
    password:
      secure: f1yhswsBcXVYRpoZTakScl1gpc5bdWibEiPrYsJy+pfUiJ0tpfQIwYbSr1G+M9egl14wFF23OYQdyl7hdl8T2vuB5jw5SUwWVQOzNI/VctCtXmEahi7PaxEHME0OAZoRQU7uNySPu/Dt//42UkdLjwB77x25KAjRP8quRauy4pSgXWpTrDpwAm6+aVj6EkDvMn9cGY5etVuCpMYUx0YFs47BZI9wH5YvGaX8pz/Gw25H7aXYqaYKzLsol08l459fOe2M2NLE/KJLjYazKHWtL/1HMxKUSOuXMIt+Lb9MoRGTuVmEJupRF+I8e9bRSH37MneT9THc+kwZ2Bg57yb2xTZcJt4JQ7WdeKnTG6aGcw/2xHDE3/YISzWfvQ0pPF9byJscGbe5OJdoKgirNWYzhuui/qEuJGNrjP8FSrtGH3kFqpRg0FErcRZhfVlMlm6GL8XuR/AGvA3eCAQL2gN8Az3tJzVNps8Fmo/XKCKaO63U62USsezkmD611OJvaR8HcQlcFZBK7y+3go0t+1CXM0NmvRG3OrN6x7e79Psin8T+7eCAhpU5oc+gb+ooBWUmNYnoblipkTXv+3Dp8qSaTJ9aiWzpkCUkvGxzlnwjvV5RtYEHlan6C/Paj3clg7aQ1+W8o2L41x8og2MuCr/d6+HnCIAnGm4bQAaUK4+tOp0=
    on:
      branch: master
      tags: true
      repo: zfit/zfit-physics
      python: 3.8
#  - provider: pages
#    skip_cleanup: true
#    github_token:
#      secure: loN6oKtEEicR8O71eoeZLO7KEKjtE1EIo1FpWykbUmCB8KEFJz0KtDwwEcT9at2i3LfG6MEccaHtfTwsXycnP3YktFnFA+C0MxTgeKF1evWC1S/xED/vRr3OjczVjrhjZ4viDJmPGr4O+VaMeNf9usde9OmRBdUWUV7qhKk2CZwh8GcBH4XkbtdjQrQoXSJa4WVl6Ix0NNdQ/ckfQIt2Gw7HF2bggRdT31rGWx2FEHJUsb5632LJRCbkC/5p3N24Eqih0G472Q9DwrnZ3AqqjK+mLmFAghw6fy1992FqqH6QCZ9gbDkXmQqIQ0aL37A1S15NtDRXmj/a8uL5E76F4ybP3aKvxsPhkcTLK+ATk2rYtlAc+wD6/L+rUdKJEDZx855+aMhcS5F6mXBXjlTPLf1NU7jWcUjdIzEuLDOATmQs9EcFX3sv7sS8XB+Zrp4P2QpBHWuUlzmHqC6lVFLNSieqioHxXgvvIUyxHW5rVnkP2/FGUw0tyWtLO+8B/20d+Wdrgza2e5qmKK1s1YvmY7IkDc6IgbG8oMVnx7bsZmH7R3ZbT34T2qM7gPi5zM/C0Z+1HS5b2rG36HMlRVWEPFj+AhbnmHXCHlyUttbhcPzvYnuPspvaz4nyFXfv0JP+LMfJ+JhqExk1cKOLl6Ec4zN9z5icXAgpDeKZOViiUk8=
#    local_dir: docs/_build/html
#    keep-history: true
#    on:
#      branch: develop
#      condition: $TRAVIS_PYTHON_VERSION = "3.8" && $TRAVIS_OS_NAME = "linux"
